name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # BUILD LAMBDA
      - name: Build Lambda
        working-directory: ./go-api
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap .

      - name: Create ZIP
        working-directory: ./go-api
        run: |
          zip -r lambda.zip bootstrap

      - name: Copy ZIP to Terraform
        run: |
          cp go-api/lambda.zip terraform/lambda.zip

      # TERRAFORM
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="project_name=gestor-usuarios"

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="project_name=gestor-usuarios"